trigger:
- windows

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    filePath: 'releng\Get-ExternalTools.ps1'
- task: VSBuild@1
  displayName: "VSBuild - x64"
  inputs:
    solution: '**\*.sln'
    platform: 'x64'
    configuration: 'Release'
    clean: true
  continueOnError: true

- task: VSBuild@1
  displayName: "VSBuild - ARM64"
  inputs:
    solution: '**\*.sln'
    platform: 'ARM64'
    configuration: 'Release'
    clean: true
  continueOnError: true

- task: VSBuild@1
  displayName: "VSBuild - x86"
  inputs:
    solution: '**\*.sln'
    platform: 'x86'
    configuration: 'Release'
    clean: true
  continueOnError: true

- task: VSBuild@1
  displayName: "VSBuild - ARM"
  inputs:
    solution: '**\*.sln'
    platform: 'ARM'
    configuration: 'Release'
    clean: true
  continueOnError: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **\build\**
      !**\tmp\**\*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
