trigger:
- windows

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: "Get External Tools"
  inputs:
    filePath: 'releng\Get-ExternalTools.ps1'

- task: VSBuild@1
  displayName: "VSBuild - x64"
  inputs:
    solution: '**\*.sln'
    platform: 'x64'
    configuration: 'Release'
    clean: true

- task: CopyFiles@2
  displayName: "Copy output files"
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **\build\**
      !**\tmp\**\*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: "Publish output files"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DTrace'
    publishLocation: 'Container'

- task: ComponentGovernanceComponentDetection@0
  displayName: "Component Detection and Governance"
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
